name: CI
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use node-${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - run: npm ci
      - run: npm run lint
      - run: npm test

  versions:
    name: node-${{ matrix.node }}
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        node: [ 12, 14, 16, 18 ]
    steps:
      - uses: actions/checkout@v3
      - name: Use node-${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - run: npm ci
      - run: npm test
